const brands = [
	'Betty Basics',
	'Commoners',
	'COOP',
	'Fate + Becker',
	'George & Edi Fragrances',
	'Ketz-Ke',
	'My Boyfriends Back',
	'NYNE',
	'Privé Revaux Eyewear',
	'Ricochet',
	'Rosefield Watches',
	'Tuesday',
	'Blak',
	'Koko Body',
	'Marle',
	'Remain',
	'Karen Walker Fragrances',
	'SOPHIE Accessories',
	'Saben',
	'Twenty Seven Names',
	'Stolen Girlfriends Club',
	'Assembly Label',
	'Rejuvenated Collagen',
	'Clique Fitness',
	'Rue Stiic',
	'Good & Co Scarves',
	'Carly Paiker Jewellery',
	'AGE Eyewear',
	'Widdess',
	'ONETEASPOON',
	'Thing Thing',
	'Millie Askew',
	'Rails',
	'Who Is Elijah Eau De Parfum',
	'Rains',
	'Caitlin Crisp',
	'Camilla & Marc',
	'Blanca',
	'Buttermilk Accessories',
	'Summery Copenhagen',
]

export default brands